apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rss-account-service-monitor
  namespace: rss-account 
  labels:
    app: rss-account-service 
    release: kube-prometheus-stack
    team: rss-account-service
spec:
  selector:
    matchLabels:
      app: rss-account-service 
  namespaceSelector:
    matchNames: 
    - rss-account
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 10s
